// The after-dark cards: sex, drink, drugs, death, church and bodily fluids --
// the kind of thing the game is known for. Written for this project. Never
// picked unless somebody picks them. What they leave out on purpose is jokes
// at the expense of who people are.

import type { Pack } from "./cah-packs";

export const PACK_EN_ADULT: Pack = {
  name: "after dark (English, 18+)",
  adult: true,
  black: [
    "What's the real reason Grandpa got banned from the care home? ____.",
    "I never understood true love until I experienced ____.",
    "The doctor held up my X-ray and asked, is that ____?",
    "What did I do with my body during lockdown? ____.",
    "The only thing standing between me and a felony is ____.",
    "What's the safe word? ____.",
    "What ended my last relationship? ____.",
    "What did Vegas give me that penicillin can't fix? ____.",
    "____: the leading cause of death among people who say hold my beer.",
    "My sex tape was ruined by ____.",
    "The priest said I could be forgiven for anything except ____.",
    "Instead of therapy, I use ____.",
    "My last text before blacking out: ____.",
    "What's my OnlyFans about? ____.",
    "What does Satan do on his day off? ____.",
    "At my funeral, I want everyone to remember ____.",
    "Mum, Dad, I'm pregnant. And the father is ____.",
    "In prison, the currency is ____.",
    "Why did I get thrown out of the orgy? ____.",
    "The coroner's report just says ____.",
    "The worst thing to hear during sex: ____.",
    "What did the stripper whisper in my ear? ____.",
    "____ and ____: the two things my divorce lawyer told me never to mention.",
    "What's the secret to a long marriage? ____.",
    "Hey Siri, how do I get rid of ____?",
    "Why is my search history encrypted? ____.",
    "The hospital bill had a line for ____.",
    "The worst thing to find in a motel bed: ____.",
    "I'm not an alcoholic. I just really enjoy ____.",
    "What gets me through a hangover? ____.",
    "What is God's biggest regret? ____.",
    "I lost my virginity to ____.",
    "Why won't the dog look me in the eye anymore? ____.",
    "What made the dominatrix quit? ____.",
    "What did the autopsy find in my stomach? ____.",
    "My dating profile says I love long walks and ____.",
    "Tonight's special: ____, with a side of ____.",
    "What will I never do sober again? ____.",
    "What's hidden behind the painting in my bedroom? ____.",
    "What killed the mood at the swingers' party? ____.",
    "The office Secret Santa went to HR because of ____.",
    "What's on the USB stick I'll take to my grave? ____.",
    "My nan died doing what she loved: ____.",
    "What did the Uber driver see in the back seat? ____.",
    "The motel charged me extra for ____.",
    "At the gender reveal, instead of pink or blue, out came ____.",
  ],
  white: [
    "Explosive diarrhoea on a first date.",
    "Dad's secret second family.",
    "A lifetime supply of lube.",
    "Crying during sex.",
    "Getting hammered at a christening.",
    "The walk of shame at seven in the morning.",
    "An STD with a cute name.",
    "The Google reviews of my sex dungeon.",
    "A hot priest.",
    "A boner in a job interview.",
    "Faking my own death to leave the family group chat.",
    "Seven shots of tequila and one bad decision.",
    "Sending nudes to the family group chat.",
    "Grandma's surprisingly active Tinder.",
    "A threesome with regrets.",
    "Crotch sweat.",
    "Being haunted by my ex's mother.",
    "Make-up sex at a funeral.",
    "A drug dealer with a loyalty card.",
    "Sexting the wrong number.",
    "My incognito tabs.",
    "Tax fraud.",
    "A selfie with the open casket.",
    "Dying alone and being eaten by my cats.",
    "A discount vasectomy.",
    "Period sex.",
    "The body in my boot.",
    "Hooking up at a wake.",
    "A horny clown.",
    "Butt stuff.",
    "A spicy colonoscopy.",
    "Getting high with a nun.",
    "Anal bleaching.",
    "A dick pic nobody asked for.",
    "Edibles at a baby shower.",
    "A crippling scratch-card habit.",
    "Being the reason the priest drinks.",
    "A demon living in my genitals.",
    "Sleeping with the boss for a better stapler.",
    "Midlife-crisis sex.",
    "My mother-in-law's nudes.",
    "Whatever is growing in my armpit.",
    "Chlamydia.",
    "A funeral with an open bar.",
    "Selling a kidney for concert tickets.",
    "Finishing in eleven seconds.",
    "Toe sucking.",
    "Bathtub gin.",
    "A suspiciously crunchy gym sock.",
    "An erection lasting more than four hours.",
    "Getting off to the weather forecast.",
    "A priest with an OnlyFans.",
    "Shame.",
    "My late grandmother's vibrator.",
    "Pooping in the shower.",
    "Waking up next to a stranger in a mascot costume.",
    "Getting stoned in church.",
    "A hangover that became a personality.",
    "My hairy back.",
    "Dying on the toilet.",
    "Accidentally sexting my priest.",
    "Blackout karaoke at a wake.",
    "Court-ordered anger management.",
    "My probation officer.",
    "Laundering money through a car wash.",
    "Getting caught by the robot vacuum mid-wank.",
    "Haemorrhoids.",
    "A sex swing and a weak ceiling.",
    "The smell of regret and cheap vodka.",
    "Losing my virginity in the back of a Fiat.",
    "My ex's mugshot.",
    "Tentacle porn.",
    "A line of coke off a toilet seat.",
    "Hooking up with a mime. It was very quiet.",
    "A condom full of ranch dressing.",
    "Being slapped with a fish during sex.",
    "A surprise prostate exam.",
    "Pubes on the soap.",
    "A satanic ritual that was far too polite.",
    "Getting sober and regretting it immediately.",
    "Selling feet pics to fund my pension.",
    "Murder, but tasteful.",
    "Burying the evidence under the patio.",
    "A very, very specific fetish.",
    "Crying into a bucket of fried chicken.",
    "The playlist for my own funeral.",
    "A boner at a funeral.",
    "Morning-breath sex.",
    "Drunk-texting God.",
    "Hell's customer service line.",
    "A skeleton in the loft.",
    "The Devil's OnlyFans.",
    "Hot wax in the wrong place.",
    "My balls.",
    "Tits.",
    "Dying a virgin.",
    "A rash that spells a word.",
    "Being too ugly for witness protection.",
    "The morning-after pill and a mimosa.",
    "A drunk surgeon.",
    "Projectile vomiting on a rollercoaster.",
    "A pregnancy test in the office bin.",
    "My sugar daddy's wife.",
    "Getting dumped by voice note.",
    "A threesome with the Holy Trinity.",
    "A honeymoon suite with a jacuzzi and cockroaches.",
    "Shagging in a portaloo.",
    "Pulling my best friend's ex.",
    "A nude with my mum in the mirror behind me.",
    "Magic mushrooms at Grandma's birthday.",
    "A tattoo of my ex's name.",
    "Falling asleep on the night bus and waking up somewhere else without pants.",
    "A televangelist's private jet.",
    "Peeing in the hotel pool.",
    "The leaked audio from the orgy.",
    "A piercing in the place we don't talk about.",
    "Whisky breath at nine in the morning.",
    "Getting a lap dance from my dentist.",
    "An intervention with a cash bar.",
    "My dealer's baby shower.",
    "Explaining the stain on the hotel ceiling.",
  ],
};

export const PACK_PT_ADULT: Pack = {
  name: "depois da meia-noite (português, 18+)",
  adult: true,
  black: [
    "Por que o vovô foi expulso do asilo? ____.",
    "Eu nunca entendi o amor de verdade até experimentar ____.",
    "O médico levantou meu raio-x e perguntou: isso aqui é ____?",
    "O que eu fiz com meu corpo durante a quarentena? ____.",
    "A única coisa entre mim e um crime inafiançável é ____.",
    "Qual é a palavra de segurança? ____.",
    "O que acabou com meu último namoro? ____.",
    "O que eu trouxe do Carnaval que nem a penicilina resolve? ____.",
    "____: a principal causa de morte entre quem fala 'segura minha cerveja'.",
    "Meu vídeo íntimo foi arruinado por ____.",
    "O padre disse que eu posso ser perdoado por tudo, menos por ____.",
    "No lugar da terapia, eu uso ____.",
    "Minha última mensagem antes do apagão: ____.",
    "Do que é o meu OnlyFans? ____.",
    "O que o capeta faz na folga dele? ____.",
    "No meu velório, quero que todo mundo lembre de ____.",
    "Mãe, pai, tô grávida. E o pai é ____.",
    "Na cadeia, a moeda é ____.",
    "Por que eu fui expulso da suruba? ____.",
    "O laudo do IML diz só isso: ____.",
    "A pior coisa de ouvir na hora H: ____.",
    "O que a stripper sussurrou no meu ouvido? ____.",
    "____ e ____: as duas coisas que meu advogado de divórcio mandou nunca mencionar.",
    "Qual é o segredo de um casamento longo? ____.",
    "Ô Siri, como é que eu me livro de ____?",
    "Por que meu histórico é criptografado? ____.",
    "A conta do hospital cobrava ____.",
    "A pior coisa de achar numa cama de motel: ____.",
    "Eu não sou alcoólatra. Eu só gosto muito de ____.",
    "O que me salva da ressaca? ____.",
    "Qual é o maior arrependimento de Deus? ____.",
    "Perdi a virgindade com ____.",
    "Por que o cachorro não me olha mais nos olhos? ____.",
    "O que fez a dominatrix pedir demissão? ____.",
    "O que a autópsia achou no meu estômago? ____.",
    "Meu perfil no app de namoro diz que eu curto caminhadas e ____.",
    "Prato do dia: ____, acompanhado de ____.",
    "O que eu nunca mais faço sóbrio? ____.",
    "O que tem escondido atrás do quadro do meu quarto? ____.",
    "O que acabou com o clima na festa de swing? ____.",
    "O amigo secreto da firma foi parar no RH por causa de ____.",
    "O que tem no pendrive que eu vou levar pro túmulo? ____.",
    "Minha avó morreu fazendo o que amava: ____.",
    "O que o motorista do Uber viu no banco de trás? ____.",
    "O motel cobrou taxa extra por causa de ____.",
    "No chá revelação, em vez de rosa ou azul, saiu ____.",
    "O que o pastor fez com o dízimo? ____.",
    "Porra, quem deixou ____ no banheiro da firma?",
  ],
  white: [
    "Diarreia explosiva no primeiro encontro.",
    "A segunda família secreta do meu pai.",
    "Um estoque vitalício de lubrificante.",
    "Chorar durante o sexo.",
    "Encher a cara no batizado.",
    "A caminhada da vergonha às sete da manhã.",
    "Uma DST com nome fofo.",
    "As avaliações do meu quartinho do prazer no Google.",
    "Um padre gostoso.",
    "Ficar de pau duro na entrevista de emprego.",
    "Fingir a própria morte pra sair do grupo da família.",
    "Sete doses de cachaça e uma decisão ruim.",
    "Mandar nude no grupo da família.",
    "O Tinder surpreendentemente ativo da vovó.",
    "Um ménage com arrependimento.",
    "Suor no saco.",
    "Ser assombrado pela ex-sogra.",
    "Sexo de reconciliação no velório.",
    "Um traficante com cartão fidelidade.",
    "Mandar putaria pro número errado.",
    "A aba anônima do meu navegador.",
    "Sonegação de imposto.",
    "Selfie com o caixão aberto.",
    "Morrer sozinho e ser comido pelos meus gatos.",
    "Vasectomia em clínica de promoção.",
    "Sexo na menstruação.",
    "O corpo no porta-malas.",
    "Pegação no velório.",
    "Um palhaço tarado.",
    "Fio terra.",
    "Uma colonoscopia apimentada.",
    "Fumar um com a freira.",
    "Clareamento anal.",
    "Uma foto de pinto que ninguém pediu.",
    "Brigadeiro batizado no chá de bebê.",
    "Um vício em raspadinha.",
    "Ser o motivo do padre beber.",
    "Um demônio morando nas minhas partes.",
    "Dar pro chefe por um grampeador melhor.",
    "Sexo de crise de meia-idade.",
    "Os nudes da minha sogra.",
    "Seja lá o que tá crescendo no meu sovaco.",
    "Clamídia.",
    "Velório com open bar.",
    "Vender um rim pra ir no show.",
    "Terminar em onze segundos.",
    "Chupar dedo do pé.",
    "Cachaça de alambique clandestino.",
    "Uma meia de academia suspeitamente crocante.",
    "Uma ereção de mais de quatro horas.",
    "Bater uma vendo a previsão do tempo.",
    "Um padre com OnlyFans.",
    "Vergonha.",
    "O vibrador da minha avó falecida.",
    "Fazer cocô no banho.",
    "Acordar do lado de um desconhecido fantasiado de mascote.",
    "Ficar chapado na missa.",
    "Uma ressaca que virou personalidade.",
    "Minhas costas peludas.",
    "Morrer no vaso sanitário.",
    "Mandar nude pro padre sem querer.",
    "Karaokê bêbado no velório.",
    "Curso de controle da raiva por ordem judicial.",
    "Meu oficial da condicional.",
    "Lavar dinheiro num lava-jato.",
    "Ser pego batendo uma pelo aspirador robô.",
    "Hemorroida.",
    "Um balanço erótico e um teto fraco.",
    "O cheiro de arrependimento e vodka barata.",
    "Perder a virgindade num Gol quadrado.",
    "A foto de fichamento do meu ex.",
    "Hentai de tentáculo.",
    "Cheirar uma carreira na tampa do vaso.",
    "Pegar um mímico. Foi bem silencioso.",
    "Uma camisinha cheia de maionese.",
    "Levar um peixe na cara durante o sexo.",
    "Um exame de próstata surpresa.",
    "Pentelho no sabonete.",
    "Um ritual satânico educado demais.",
    "Ficar sóbrio e se arrepender na hora.",
    "Vender foto de pé pra pagar a aposentadoria.",
    "Assassinato, mas com bom gosto.",
    "Enterrar as provas no quintal.",
    "Um fetiche muito, muito específico.",
    "Chorar num balde de frango frito.",
    "A playlist do meu próprio velório.",
    "Ficar de pau duro no velório.",
    "Sexo com bafo de manhã.",
    "Mandar mensagem bêbado pra Deus.",
    "O SAC do inferno.",
    "Um esqueleto no forro da casa.",
    "O OnlyFans do capeta.",
    "Cera quente no lugar errado.",
    "Meu saco.",
    "Peitos.",
    "Morrer virgem.",
    "Uma alergia que forma uma palavra.",
    "Ser feio demais pro programa de proteção à testemunha.",
    "A pílula do dia seguinte com um drinque.",
    "Um cirurgião bêbado.",
    "Vomitar em jato na montanha-russa.",
    "Um teste de gravidez no lixo da firma.",
    "A esposa do meu sugar daddy.",
    "Levar um pé na bunda por áudio.",
    "Um ménage com a Santíssima Trindade.",
    "Motel com hidromassagem e barata.",
    "Transar no banheiro químico do bloquinho.",
    "Pegar o ex da melhor amiga.",
    "Um nude com a minha mãe no reflexo do espelho.",
    "Chá de cogumelo no aniversário da vó.",
    "A tatuagem com o nome da ex.",
    "Dormir no ônibus e acordar em outra cidade sem cueca.",
    "Um pastor de Lamborghini.",
    "Fazer xixi na piscina do clube.",
    "O áudio vazado da suruba.",
    "Um piercing no lugar que não se fala.",
    "Bafo de cachaça às nove da manhã.",
    "Uma lap dance do meu dentista.",
    "Uma intervenção com open bar.",
    "O chá de bebê do meu traficante.",
    "Explicar a mancha no teto do motel.",
    "O tiozão do churrasco sem camisa e sem limites.",
    "Um bloco de Carnaval que terminou na delegacia.",
  ],
};
