// Starter cards for the party game, written for this project. The table can
// play with these, with its own, or with both. A prompt's blanks are written
// as four underscores; a prompt with none takes one answer at the end.

export interface Pack {
  name: string;
  black: string[];
  white: string[];
}

export const PACK_EN: Pack = {
  name: "starter (English)",
  black: [
    "What ruined the family barbecue this year? ____.",
    "My therapist says I need to stop thinking about ____.",
    "The secret ingredient in grandma's soup is ____.",
    "Breaking news: scientists can finally explain ____.",
    "What's that smell? ____.",
    "I got thrown out of the library for ____.",
    "Nobody warned me that being an adult is mostly ____.",
    "The next big fitness trend: ____.",
    "What did I find down the back of the sofa? ____.",
    "My love language is ____.",
    "The group chat went quiet after someone sent ____.",
    "Instead of a gold watch, I retired with ____.",
    "The museum's newest exhibit: ____.",
    "Today's horoscope: avoid ____ at all costs.",
    "I would sell my soul for ____. But only a little bit of it.",
    "The villain's master plan depends entirely on ____.",
    "What's hiding at the back of the fridge? ____.",
    "Step one: ____. Step two: ____. Step three: profit.",
    "I can never go back to that hotel because of ____.",
    "My landlord says the rent is going up because of ____.",
    "The wedding was lovely until ____.",
    "My last three brain cells are fighting over ____.",
    "____ meets ____: the crossover nobody asked for.",
    "What's my secret superpower? ____.",
    "What did the cat knock off the table this time? ____.",
    "The pirate buried ____ and told nobody where.",
    "The worst thing to hear from your dentist: ____.",
    "New post on LinkedIn: what ____ taught me about sales.",
    "What's in the mystery box? ____.",
    "My plan for the zombie apocalypse: ____.",
    "The office is closed today because of ____.",
    "I'm not crying. It's just ____.",
    "Coming soon to a theatre near you: ____, the musical.",
    "What am I bringing to the potluck? ____.",
    "I asked the genie for world peace. He gave me ____.",
    "The Olympic committee has approved ____ as a sport.",
    "This year, instead of presents, the family agreed on ____.",
    "Mum found ____ in my search history.",
    "Why am I sticky? ____.",
    "What did the fortune cookie say? ____.",
    "My ex is dating ____ now.",
    "The robot uprising started with ____.",
    "I mixed ____ with ____ and now I don't have a kitchen.",
    "Why is the neighbour's dog screaming? ____.",
    "Just unlocked a brand new fear: ____.",
    "The residents' meeting turned violent over ____.",
    "Nothing says romance like ____.",
    "What got me through the Monday meeting? ____.",
  ],
  white: [
    "A suspiciously confident pigeon.",
    "Grandma's search history.",
    "Eleven raccoons in a trench coat.",
    "An emotional support cactus.",
    "The last slice of pizza.",
    "Aggressive jazz hands.",
    "A tax audit.",
    "Crying in the supermarket car park.",
    "Mildly haunted furniture.",
    "A strongly worded email.",
    "The very concept of Mondays.",
    "Accidentally liking a photo from 2014.",
    "A goose with a knife.",
    "Microwaving fish at the office.",
    "Advice nobody asked for.",
    "Pretending to understand wine.",
    "Being perceived.",
    "Lukewarm tap water.",
    "A group project.",
    "Saying 'you too' to the waiter.",
    "Forty-seven open browser tabs.",
    "The Wi-Fi password.",
    "A dramatic key change.",
    "Losing a flip-flop at sea.",
    "A life coach who has never had a life.",
    "Interpretive dance.",
    "An unexpected item in the bagging area.",
    "A sourdough starter with a first and last name.",
    "Cursed clogs.",
    "Screaming into a pillow.",
    "Pineapple on pizza.",
    "A cryptocurrency with a dog on it.",
    "The ghost of a Victorian child.",
    "Tiny hats for frogs.",
    "A clown on his lunch break.",
    "The word 'moist'.",
    "Yodelling.",
    "The endless void.",
    "A possessed robot vacuum.",
    "A hug that goes on for far too long.",
    "Sneezing in a job interview.",
    "Eating cereal with a fork.",
    "Three kids pretending to be one adult.",
    "A sad trombone.",
    "The disappointment of the self-checkout.",
    "Soup.",
    "Forgetting someone's name mid-sentence.",
    "A wizard with student debt.",
    "Glitter. Everywhere. Forever.",
    "Getting lost in a warehouse store.",
    "Aunt Linda's opinions.",
    "An advert you can't skip.",
    "A midlife crisis, speedrun edition.",
    "A llama that knows too much.",
    "The fourth wall.",
    "A sword I bought at a renaissance fair.",
    "Karaoke at three in the morning.",
    "Mayonnaise-flavoured ice cream.",
    "Swimming straight after lunch.",
    "A speaker blasting music on the bus.",
    "A very small horse.",
    "Replying all to the whole company.",
    "Bees?",
    "My one remaining brain cell.",
    "Existential dread, but make it fashion.",
    "The noise a dial-up modem makes.",
    "Stepping on a building brick barefoot.",
    "A haunted doll with a podcast.",
    "Discount sushi.",
    "The gym membership I never use.",
    "A surprise bagpipe solo.",
    "Being frighteningly good at Tetris.",
    "An inflatable tube man.",
    "A self-aware casserole.",
    "Emotional damage.",
    "My tragic backstory.",
    "A cowboy with no horse.",
    "The floor being lava.",
    "An unpaid internship at a volcano.",
    "Divorcing my houseplants.",
    "Whispering 'enhance' at a blurry photo.",
    "Socks with sandals.",
    "Popcorn at two in the morning.",
    "A duck in a business suit.",
    "Buying a boat.",
    "The side quest.",
    "A fax machine.",
    "Being famous in one small town.",
    "Airport sushi.",
    "A fitted sheet that refuses to fold.",
    "Inventing a new colour.",
    "The neighbour's parrot, who swears.",
    "Doing my taxes in crayon.",
    "Crying at a car advert.",
    "A mirror that is slightly too honest.",
    "Main character energy.",
    "A bucket of warm spaghetti.",
    "Accidentally joining a cult.",
    "Being chased by a swan.",
    "A vending machine that keeps your money and your dignity.",
    "Whatever is in the tub at the back of the freezer.",
    "Tactical napping.",
    "Unfolding a map in the wind.",
    "A haunted spreadsheet.",
    "Opening a door with my face.",
    "A single, perfect grape.",
    "Dad jokes.",
    "A mime in real trouble.",
    "Very small spoons.",
    "Knowing every word of a song I hate.",
    "Arguing with the satnav.",
    "The family group chat.",
    "A handshake that turns into a hug.",
    "A nap that lasts three days.",
    "Inner peace, sold separately.",
    "A rubber chicken.",
    "Aggressive eye contact.",
    "Pigeons in the boardroom.",
    "A meeting that could have been an email.",
    "A seven-minute voice message.",
    "The neighbour's drum practice.",
    "An unannounced visit from the in-laws.",
    "Burnt rice at the bottom of the pan.",
    "A tub of ice cream that is secretly full of beans.",
    "A goat who has seen things.",
    "Winning an argument in the shower, three days later.",
    "A haunted bouncy castle.",
    "A tiny violin.",
    "An accountant who moonlights as a wrestler.",
  ],
};

export const PACK_PT: Pack = {
  name: "inicial (português)",
  black: [
    "O que estragou o churrasco de domingo? ____.",
    "Minha terapeuta pediu pra eu parar de pensar em ____.",
    "O ingrediente secreto da feijoada da vó é ____.",
    "Plantão urgente: cientistas finalmente explicam ____.",
    "Que cheiro é esse? ____.",
    "Fui expulso da biblioteca por causa de ____.",
    "Ninguém me avisou que a vida adulta é basicamente ____.",
    "A nova moda da academia: ____.",
    "O que eu achei no meio do sofá? ____.",
    "Minha linguagem do amor é ____.",
    "O grupo da família ficou em silêncio depois que alguém mandou ____.",
    "Me aposentei e ganhei ____ de presente.",
    "A nova exposição do museu: ____.",
    "Horóscopo de hoje: evite ____ a qualquer custo.",
    "Eu venderia minha alma por ____. Mas só um pedacinho.",
    "O plano do vilão depende todinho de ____.",
    "O que tem escondido no fundo da geladeira? ____.",
    "Passo um: ____. Passo dois: ____. Passo três: lucro.",
    "Não posso nunca mais voltar naquele hotel por causa de ____.",
    "O aluguel subiu por causa de ____.",
    "O casamento estava lindo até ____.",
    "Meus três últimos neurônios estão brigando por ____.",
    "____ encontra ____: o crossover que ninguém pediu.",
    "Qual é o meu superpoder secreto? ____.",
    "O que o gato derrubou da mesa dessa vez? ____.",
    "O pirata enterrou ____ e não contou pra ninguém onde.",
    "A pior coisa de ouvir do dentista: ____.",
    "Novo post no LinkedIn: o que ____ me ensinou sobre vendas.",
    "O que tem na caixa misteriosa? ____.",
    "Meu plano para o apocalipse zumbi: ____.",
    "Não teve expediente hoje por causa de ____.",
    "Não tô chorando. É só ____.",
    "Em breve nos cinemas: ____, o musical.",
    "O que eu vou levar pra festa junina? ____.",
    "Pedi paz mundial pro gênio. Ele me deu ____.",
    "O comitê olímpico aprovou ____ como esporte.",
    "Esse Natal, no lugar do amigo secreto, a família combinou ____.",
    "Minha mãe achou ____ no meu histórico.",
    "Por que eu tô grudento? ____.",
    "O que dizia o biscoito da sorte? ____.",
    "Meu ex agora namora ____.",
    "A rebelião das máquinas começou com ____.",
    "Misturei ____ com ____ e agora não tenho mais cozinha.",
    "Por que o cachorro do vizinho está gritando? ____.",
    "Acabei de desbloquear um medo novo: ____.",
    "A reunião de condomínio acabou em briga por causa de ____.",
    "Nada é mais romântico que ____.",
    "O que o tio do pavê falou dessa vez? ____.",
  ],
  white: [
    "Um pombo confiante demais.",
    "O histórico de pesquisa da vó.",
    "Onze guaxinins dentro de um sobretudo.",
    "Um cacto de apoio emocional.",
    "O último pedaço de pizza.",
    "Uma malha fina da Receita.",
    "Chorar no estacionamento do mercado.",
    "Um móvel levemente assombrado.",
    "Um e-mail passivo-agressivo.",
    "O conceito de segunda-feira.",
    "Curtir sem querer uma foto de 2014.",
    "Um ganso armado com uma faca.",
    "Esquentar peixe no micro-ondas do escritório.",
    "Conselho que ninguém pediu.",
    "Fingir que entende de vinho.",
    "Ser percebido.",
    "Água morna da torneira.",
    "Trabalho em grupo.",
    "Responder 'você também' pro garçom.",
    "Quarenta e sete abas abertas.",
    "A senha do Wi-Fi.",
    "Perder o chinelo no mar.",
    "Um coach que nunca foi motivado.",
    "Dança contemporânea.",
    "Um item inesperado na área de embalagem.",
    "Um fermento natural com nome e sobrenome.",
    "Crocs amaldiçoadas.",
    "Gritar no travesseiro.",
    "Pizza com abacaxi.",
    "Uma criptomoeda com cara de cachorro.",
    "O fantasma de uma criança do século XIX.",
    "Chapeuzinhos para sapos.",
    "Um palhaço no horário de almoço.",
    "A palavra 'úmido'.",
    "Um aspirador robô possuído.",
    "Um abraço que dura tempo demais.",
    "Espirrar na entrevista de emprego.",
    "Comer cereal de garfo.",
    "Um trombone triste.",
    "Sopa.",
    "Esquecer o nome da pessoa no meio da frase.",
    "Um mago com dívida estudantil.",
    "Glitter. Em todo lugar. Pra sempre.",
    "Se perder no atacadão.",
    "As opiniões da tia Nair.",
    "Um anúncio que não dá pra pular.",
    "Uma crise de meia-idade em modo speedrun.",
    "Uma lhama que sabe demais.",
    "A quarta parede.",
    "Karaokê às três da manhã.",
    "Sorvete sabor maionese.",
    "Entrar no mar logo depois do almoço.",
    "Caixinha de som no ônibus.",
    "Um cavalo muito pequeno.",
    "Responder a todos no e-mail da empresa.",
    "Abelhas?",
    "Meu último neurônio.",
    "O barulho da internet discada.",
    "Pisar numa pecinha de montar descalço.",
    "Uma boneca assombrada com podcast.",
    "Rodízio de sushi às onze da noite.",
    "A academia que eu pago e não vou.",
    "Um solo surpresa de gaita de fole.",
    "Aquele boneco inflável de posto de gasolina.",
    "Uma torta de frango com consciência.",
    "Dano emocional.",
    "Minha história triste de origem.",
    "Um caubói sem cavalo.",
    "O chão é lava.",
    "Estágio não remunerado num vulcão.",
    "Me divorciar das minhas plantas.",
    "Meia com sandália.",
    "Pipoca de micro-ondas às duas da manhã.",
    "Um pato de terno e gravata.",
    "Comprar um barco.",
    "A missão secundária.",
    "Um aparelho de fax.",
    "Ser famoso só no bairro.",
    "Um lençol de elástico que se recusa a dobrar.",
    "Inventar uma cor nova.",
    "O papagaio do vizinho, que xinga.",
    "Declarar imposto de renda com giz de cera.",
    "Chorar com comercial de margarina.",
    "Um espelho sincero demais.",
    "Energia de protagonista.",
    "Um balde de miojo morno.",
    "Entrar numa seita sem querer.",
    "Ser perseguido por um ganso.",
    "Uma máquina de salgadinho que come seu dinheiro e sua dignidade.",
    "O pote de sorvete que na verdade tem feijão.",
    "Cochilo tático.",
    "Abrir a porta com a cara.",
    "Uma uva perfeita.",
    "Piada de tiozão.",
    "Um mímico em apuros de verdade.",
    "Colherzinhas muito pequenas.",
    "Saber a letra inteira de uma música que eu odeio.",
    "Discutir com o GPS.",
    "O grupo da família.",
    "Um aperto de mão que vira abraço.",
    "Um cochilo de três dias.",
    "Paz interior, vendida separadamente.",
    "Uma galinha de borracha.",
    "Contato visual agressivo.",
    "Pombos numa reunião de diretoria.",
    "O tio do pavê.",
    "Fila de banco na segunda-feira.",
    "Carro de som às sete da manhã.",
    "Pão de queijo requentado.",
    "O Wi-Fi da rodoviária.",
    "Figurinha repetida.",
    "Um cachorro caramelo com cargo de gerência.",
    "A vizinha que sabe de tudo.",
    "Um boleto vencido.",
    "Fila do Detran.",
    "O chinelo voador da mãe.",
    "A marmita do colega de trabalho.",
    "Horário eleitoral gratuito.",
    "Uma capivara zen.",
    "Guaraná quente.",
    "Uma reunião que podia ser um e-mail.",
    "O pagode do vizinho no domingo.",
    "Um áudio de sete minutos.",
    "Visita surpresa da sogra.",
    "Arroz queimado no fundo da panela.",
    "Um sofá coberto de plástico.",
    "Um bode que já viu coisas.",
    "Ganhar uma discussão no banho, três dias depois.",
  ],
};

export const PACKS = { en: PACK_EN, pt: PACK_PT } as const;
export type PackId = keyof typeof PACKS;
