// Fonts for text on the canvas.
//
// Two kinds. The bundled ones live in public/fonts, under licences that let
// them be shared (see public/fonts/NOTICE.txt), and show for everyone. The
// installed ones are only names -- the fonts on the machine this project was
// made on, and the ones Windows comes with. Those are never copied here, since
// most of them may not be passed on; a screen that has one installed shows
// it, and any other falls back to the room's own font.

export interface BundledFont {
  family: string;
  file: string;
  format: "truetype" | "opentype";
}

export const BUNDLED_FONTS: BundledFont[] = [
  { family: "Blackcraft", file: "blackcraft.ttf", format: "truetype" },
  { family: "Help Me", file: "helpme.ttf", format: "truetype" },
  { family: "Hina Mincho", file: "hina-mincho-regular.ttf", format: "truetype" },
  { family: "Itim", file: "itim-regular.ttf", format: "truetype" },
  { family: "Manbow Clear", file: "manbow-clear.otf", format: "opentype" },
  { family: "Manbow Dots", file: "manbow-dots.otf", format: "opentype" },
  { family: "Manbow Fill", file: "manbow-fill.otf", format: "opentype" },
  { family: "Manbow Lines", file: "manbow-lines.otf", format: "opentype" },
  { family: "Manbow Screen", file: "manbow-screen.otf", format: "opentype" },
  { family: "Operational Amplifier", file: "operational-amplifier.otf", format: "opentype" },
];

/** Fonts named, not shipped: they show where they are installed. */
export const INSTALLED_FONTS: string[] = [
  "Agefin Regad trial",
  "Agency FB",
  "Alef",
  "Algerian",
  "Alternian Alphabet",
  "Amiri",
  "Amiri Quran",
  "Arial",
  "Arial Rounded MT Bold",
  "Awesome",
  "Bahnschrift",
  "Baskerville Old Face",
  "Bauhaus 93",
  "Begerak",
  "Bell MT",
  "Berlin Sans FB",
  "Berlin Sans FB Demi",
  "Bernard MT Condensed",
  "BIZ UDGothic",
  "BIZ UDMincho",
  "BIZ UDPGothic",
  "BIZ UDPMincho",
  "Blackadder ITC",
  "Blackfang",
  "Blackout Oldskull",
  "Blood Crow",
  "Bodoni MT",
  "Boho Holiday",
  "Book Antiqua",
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "BPG Glaho",
  "Bradley Hand ITC",
  "Britannic Bold",
  "Broadway",
  "Brush Script MT",
  "Caladea",
  "Calibri",
  "Californian FB",
  "Calisto MT",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Carlito",
  "Castellar",
  "Centaur",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Chemistry",
  "Child Hood",
  "Chiller",
  "Colonna MT",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Cooper Black",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Corbel",
  "Cordelia",
  "Courier New",
  "Cream Cake",
  "Curlz MT",
  "David CLM",
  "David Libre",
  "DejaVu Math TeX Gyre",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "Dubai",
  "Easter Calligraphy",
  "Ebrima",
  "Edwardian Script ITC",
  "Elephant",
  "Embolism Spark",
  "Engravers MT",
  "Eras Bold ITC",
  "Eras Demi ITC",
  "Eras Light ITC",
  "Eras Medium ITC",
  "Faloney Script",
  "Felix Titling",
  "FireFight BB",
  "Footlight MT Light",
  "Forte",
  "Frank Ruehl CLM",
  "Frank Ruhl Hofshi",
  "Franklin Gothic Book",
  "Franklin Gothic Demi",
  "Franklin Gothic Demi Cond",
  "Franklin Gothic Heavy",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Cond",
  "Freelance Kamchatka",
  "Freestyle Script",
  "French Script MT",
  "Friday13",
  "Friday13 Bonus NFI",
  "Gabriola",
  "Gadugi",
  "Garamond",
  "Gentium Basic",
  "Gentium Book Basic",
  "Georgia",
  "Gigi",
  "Gill Sans MT",
  "Gill Sans MT Condensed",
  "Gill Sans MT Ext Condensed Bold",
  "Gill Sans Ultra Bold",
  "Gill Sans Ultra Bold Condensed",
  "Gimmicky",
  "Gloucester MT Extra Condensed",
  "Goudy Old Style",
  "Goudy Stout",
  "Haettenschweiler",
  "Harlow Solid Italic",
  "Harrington",
  "High Tower Text",
  "Hyperjump",
  "Impact",
  "Imprint MT Shadow",
  "Informal Roman",
  "Ink Free",
  "Javanese Text",
  "Jokerman",
  "Juice ITC",
  "Keerma Mahi",
  "Konflic",
  "Kotton",
  "Kristen ITC",
  "Kufiye Script",
  "Kunstler Script",
  "Leelawadee UI",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Sans Narrow",
  "Liberation Serif",
  "Linux Biolinum G",
  "Linux Libertine Display G",
  "Linux Libertine G",
  "Lucida Bright",
  "Lucida Calligraphy",
  "Lucida Console",
  "Lucida Fax",
  "Lucida Handwriting",
  "Lucida Sans",
  "Lucida Sans Typewriter",
  "Lucida Sans Unicode",
  "Magic Red",
  "Magneto",
  "Maiandra GD",
  "Malgun Gothic",
  "Marlett",
  "Matura MT Script Capitals",
  "Meiryo",
  "Meiryo UI",
  "Messy Handwritten",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei UI",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft YaHei",
  "Microsoft YaHei UI",
  "Microsoft Yi Baiti",
  "Mildest Free",
  "Milkyway DEMO",
  "MingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "MingLiU_MSCS-ExtB",
  "Miriam CLM",
  "Miriam Libre",
  "Miriam Mono CLM",
  "Mistral",
  "Mochi Boom DEMO",
  "Modern No. 20",
  "Mongolian Baiti",
  "Monotype Corsiva",
  "MS Gothic",
  "MS Mincho",
  "MS Outlook",
  "MS PGothic",
  "MS PMincho",
  "MS Reference Sans Serif",
  "MS Reference Specialty",
  "MS UI Gothic",
  "MT Extra",
  "MV Boli",
  "Myanmar Text",
  "Nachlieli CLM",
  "NCL Gasdrifo",
  "Niagara Engraved",
  "Niagara Solid",
  "Nightside Demo",
  "Nirmala Text",
  "Nirmala UI",
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Sans",
  "Noto Sans Arabic",
  "Noto Sans Armenian",
  "Noto Sans Georgian",
  "Noto Sans Hebrew",
  "Noto Sans JP",
  "Noto Sans Lao",
  "Noto Sans Lisu",
  "Noto Serif",
  "Noto Serif Armenian",
  "Noto Serif Georgian",
  "Noto Serif Hebrew",
  "Noto Serif JP",
  "Noto Serif Lao",
  "Noxis",
  "NSimSun",
  "OCR A Extended",
  "Old English Text MT",
  "OMORI_GAME",
  "OMORI_GAME2",
  "Onyx",
  "OpenSymbol",
  "Palace Script MT",
  "Palatino Linotype",
  "Palisade",
  "Papyrus",
  "Parchment",
  "Party Vibes",
  "Perpetua",
  "Perpetua Titling MT",
  "Planet Dust",
  "Playbill",
  "PMingLiU-ExtB",
  "Poor Richard",
  "Prefix",
  "Pristina",
  "Rage Italic",
  "Ravie",
  "Reem Kufi",
  "Rockwell",
  "Rockwell Condensed",
  "Rockwell Extra Bold",
  "Rubik",
  "Sans Serif Collection",
  "Scheherazade",
  "Scientific Graphics",
  "Script MT Bold",
  "Segoe Fluent Icons",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "Segoe UI Variable",
  "Showcard Gothic",
  "Sigilos De Conhecimento",
  "Signatie",
  "Simple Nathalie",
  "SimSun",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka",
  "Snap ITC",
  "Stencil",
  "Storm Gust",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Tantrum Tongue",
  "Tempus Sans ITC",
  "Times New Roman",
  "Trebuchet MS",
  "Tw Cen MT",
  "Tw Cen MT Condensed",
  "Tw Cen MT Condensed Extra Bold",
  "UD Digi Kyokasho N",
  "UD Digi Kyokasho NK",
  "UD Digi Kyokasho NP",
  "VCR OSD Mono",
  "Verdana",
  "Viner Hand ITC",
  "Vivaldi",
  "Vladimir Script",
  "Webdings",
  "Wide Latin",
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Yu Gothic",
  "Yu Gothic UI",
  "Yu Mincho",
];

/** The @font-face rules for the bundled fonts. A file is only fetched once text uses it. */
export const BUNDLED_CSS = BUNDLED_FONTS.map(
  (f) => `@font-face{font-family:"${f.family}";src:url("/fonts/${f.file}") format("${f.format}");font-display:swap;}`,
).join(" ");

/** A font name made safe to put in CSS. */
export const cssFamily = (family: string) => `"${family.replace(/["\\]/g, "")}"`;

/** The font stack for a chosen font, falling back to the room's own. */
export const fontStack = (family: string | undefined) => (family ? `${cssFamily(family)}, var(--font-sans), sans-serif` : undefined);

export const isBundled = (family: string) => BUNDLED_FONTS.some((f) => f.family === family);
